version: '3'

services:
  web:
    build: .
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja
      MYSQL_USER: usario_padrao
      MYSQL_PASSWORD: senha123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
